version: '3'
dotenv: [.env]

vars:
  PACKAGE_IMPORT_NAME: house_price
  PYTHON_VERSION: 3.11

tasks:
  create-venv:
    desc: Create a virtual environment
    cmds:
      - uv venv -p {{.PYTHON_VERSION}} .venv
    silent: false

  sync-dev:
    desc: Sync project dependencies with optionals
    cmds:
      - rm -rf .venv
      - task: create-venv
      - uv sync --extra dev